<?php

namespace app\controllers;

use app\components\BaseController;
use app\models\Category;
use app\models\Product;
use yii;
use yii\web\NotFoundHttpException;

/**
 * Class SiteController
 * @package app\controllers
 */
class CatalogueController extends BaseController
{
    public function init()
    {
        Yii::$app->params['current_page'] = 'catalogue';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCategory($category = null)
    {
        if ($category == 'multi-whey-combo') {
            $this->redirect(['/catalogue/category', 'category' => 'multi-protein'], 301);
        }

        if (!is_null($category)) {
            $category = Category::findOne(['slug' => $category, 'public' => 1]);
        } else {
            $category = Category::findOne(['id' => Yii::$app->request->get('id'), 'public' => 1]);
            
            if ($category && !empty($category->slug)) {
                return $this->redirect($category->getUrl(), 301);
            }
        }

        if (!$category) {
            throw new NotFoundHttpException();
        }

        $menu = Category::findAll(['public' => 1]);

        if ($category->isSingletaste()){
            return $this->render('category-one-taste', ['category' => $category, 'menu' => $menu]);
        } elseif ($category->isCombobox()) {
            return $this->render('category-many-taste', ['category' => $category, 'menu' => $menu]);
        } else {
            throw new NotFoundHttpException();
        }
    }

    public function actionItem($category = null, $item = null)
    {
        if (!is_null($category) && !is_null($item)) {
            $category = Category::findOne(['slug' => $category, 'public' => 1]);
            $item = Product::findOne(['category_id' => $category->id, 'slug' => $item, 'public' => 1]);
            $item->cat = $category;
        } else {
            $item = Product::findOne(['id' => Yii::$app->request->get('id'), 'public' => 1]);



            if ($item && $item->category && !empty($item->category->slug) && !empty($item->slug)) {
                $url = yii\helpers\Url::to(['catalogue/item', 'category' => $item->category->slug, 'item' => $item->slug]);
                return $this->redirect($url, 301);
            }
        }

        if (!$item) {
            throw new NotFoundHttpException();
        }

        $menu = Category::findAll(['public' => 1]);

        if ($item->isSingletaste()){
            return $this->render('item-one-taste', ['item' => $item, 'menu' => $menu]);
        } elseif ($item->isCombobox()) {
            return $this->render('item-many-taste', ['item' => $item, 'menu' => $menu]);
        } else {
            throw new NotFoundHttpException();
        }
    }
}
