<?php

namespace app\controllers;

use app\components\BaseController;
use app\models\News;
use yii;

/**
 * Class SiteController
 * @package app\controllers
 */
class NewsController extends BaseController
{
    public function init()
    {
        Yii::$app->params['current_page'] = 'news';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $list = News::find()->where(['public' => 1])->orderBy('date DESC')->all();
        return $this->render('index', ['list' => $list]);
    }

    public function actionItem()
    {
        return $this->render('item', ['news' => News::findOne(['id' => Yii::$app->request->get('id')])]);
    }
}
