<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "portion_properties".
 *
 * @property integer $id
 * @property string $name
 * @property string $value
 * @property string $value_per_100
 * @property integer $ord
 * @property integer $public
 * @property integer $portion_id
 *
 * @property Portion $portion
 */
class PortionProperties extends \yii\db\ActiveRecord
{
    public function init()
    {
        $this->ord = 0;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'portion_properties';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ord', 'public', 'portion_id'], 'integer'],
            [['name', 'value', 'value_per_100'], 'string', 'max' => 50],
            [['portion_id'], 'exist', 'skipOnError' => true, 'targetClass' => Portion::className(), 'targetAttribute' => ['portion_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'value' => 'Значение',
            'value_per_100' => 'Значение на 100 гр',
            'ord' => 'Сортировка',
            'public' => 'Опубликовано',
            'portion_id' => 'Порция',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPortion()
    {
        return $this->hasOne(Portion::className(), ['id' => 'portion_id']);
    }
}
